always_on_top: false
dark_mode: false
language: es
max_record_time: 30
microphone_index: 1
seconds_of_silence_between_lines: 0.5
speech_model: tiny
text_background: false
text_size: 24
transcribe_rate: 0.5
translate: false
transparent: false
volume_threshold: 789.4736842105249
window_height: 800.0
window_width: 817.0
